export const EXP: 6;
export const COIN: number;
export const MAX_CREATORS: number;
export const MAX_SPONSORS: number;
export const MAX_TLD: number;
export const MAX_DOMAIN: number;
export const MAX_CA_NAMING: number;
export const MAX_AIRDROP: number;
export const MAX_INITIAL: number;
export const MAX_SUBSIDY: number;
export const MAX_MONEY: number;
export const BASE_REWARD: number;
export const GENESIS_REWARD: number;
export const GENESIS_KEY: Buffer;
export const MAX_BLOCK_SIZE: 1000000;
export const MAX_RAW_BLOCK_SIZE: 4000000;
export const MAX_BLOCK_WEIGHT: 4000000;
export const MAX_BLOCK_SIGOPS: 80000;
export const MAX_BLOCK_OPENS: 300;
export const MAX_BLOCK_UPDATES: 600;
export const MAX_BLOCK_RENEWALS: 600;
export const MEDIAN_TIMESPAN: 11;
export const WITNESS_SCALE_FACTOR: 4;
export const MAX_TX_SIZE: 1000000;
export const MAX_TX_WEIGHT: 4000000;
export const LOCKTIME_FLAG: number;
export const LOCKTIME_MASK: number;
export const LOCKTIME_GRANULARITY: 9;
export const LOCKTIME_MULT: number;
export const SEQUENCE_DISABLE_FLAG: number;
export const SEQUENCE_TYPE_FLAG: number;
export const SEQUENCE_GRANULARITY: 9;
export const SEQUENCE_MASK: 65535;
export const MAX_SCRIPT_SIZE: 10000;
export const MAX_SCRIPT_STACK: 1000;
export const MAX_SCRIPT_PUSH: 520;
export const MAX_SCRIPT_OPS: 201;
export const MAX_MULTISIG_PUBKEYS: 20;
export const ZERO_HASH: Buffer;
export const HEADER_SIZE: 236;
export const NONCE_SIZE: 24;
export const ZERO_HEADER: Buffer;
export const ZERO_NONCE: Buffer;
export function fromCompact(compact: number): BN;
export function toCompact(num: BN): number;
export function verifyPOW(hash: Hash, bits: number): boolean;
export function getReward(height: number, interval: any): Amount;
export function hasBit(version: number, bit: number): boolean;
