export namespace main {
    const version: number;
    const hash: Buffer;
    const prevBlock: Buffer;
    const merkleRoot: Buffer;
    const witnessRoot: Buffer;
    const treeRoot: Buffer;
    const reservedRoot: Buffer;
    const time: number;
    const bits: number;
    const nonce: number;
    const extraNonce: Buffer;
    const mask: Buffer;
    const height: number;
    const magic: number;
}
export const mainData: Buffer;
export namespace testnet {
    const version_1: number;
    export { version_1 as version };
    const hash_1: Buffer;
    export { hash_1 as hash };
    const prevBlock_1: Buffer;
    export { prevBlock_1 as prevBlock };
    const merkleRoot_1: Buffer;
    export { merkleRoot_1 as merkleRoot };
    const witnessRoot_1: Buffer;
    export { witnessRoot_1 as witnessRoot };
    const treeRoot_1: Buffer;
    export { treeRoot_1 as treeRoot };
    const reservedRoot_1: Buffer;
    export { reservedRoot_1 as reservedRoot };
    const time_1: number;
    export { time_1 as time };
    const bits_1: number;
    export { bits_1 as bits };
    const nonce_1: number;
    export { nonce_1 as nonce };
    const extraNonce_1: Buffer;
    export { extraNonce_1 as extraNonce };
    const mask_1: Buffer;
    export { mask_1 as mask };
    const height_1: number;
    export { height_1 as height };
    const magic_1: number;
    export { magic_1 as magic };
}
export const testnetData: Buffer;
export namespace regtest {
    const version_2: number;
    export { version_2 as version };
    const hash_2: Buffer;
    export { hash_2 as hash };
    const prevBlock_2: Buffer;
    export { prevBlock_2 as prevBlock };
    const merkleRoot_2: Buffer;
    export { merkleRoot_2 as merkleRoot };
    const witnessRoot_2: Buffer;
    export { witnessRoot_2 as witnessRoot };
    const treeRoot_2: Buffer;
    export { treeRoot_2 as treeRoot };
    const reservedRoot_2: Buffer;
    export { reservedRoot_2 as reservedRoot };
    const time_2: number;
    export { time_2 as time };
    const bits_2: number;
    export { bits_2 as bits };
    const nonce_2: number;
    export { nonce_2 as nonce };
    const extraNonce_2: Buffer;
    export { extraNonce_2 as extraNonce };
    const mask_2: Buffer;
    export { mask_2 as mask };
    const height_2: number;
    export { height_2 as height };
    const magic_2: number;
    export { magic_2 as magic };
}
export const regtestData: Buffer;
export namespace simnet {
    const version_3: number;
    export { version_3 as version };
    const hash_3: Buffer;
    export { hash_3 as hash };
    const prevBlock_3: Buffer;
    export { prevBlock_3 as prevBlock };
    const merkleRoot_3: Buffer;
    export { merkleRoot_3 as merkleRoot };
    const witnessRoot_3: Buffer;
    export { witnessRoot_3 as witnessRoot };
    const treeRoot_3: Buffer;
    export { treeRoot_3 as treeRoot };
    const reservedRoot_3: Buffer;
    export { reservedRoot_3 as reservedRoot };
    const time_3: number;
    export { time_3 as time };
    const bits_3: number;
    export { bits_3 as bits };
    const nonce_3: number;
    export { nonce_3 as nonce };
    const extraNonce_3: Buffer;
    export { extraNonce_3 as extraNonce };
    const mask_3: Buffer;
    export { mask_3 as mask };
    const height_3: number;
    export { height_3 as height };
    const magic_3: number;
    export { magic_3 as magic };
}
export const simnetData: Buffer;
