export const ChainDB: typeof import("./chaindb");
export const ChainEntry: typeof import("./chainentry");
export const Chain: typeof import("./chain");
export const common: typeof import("./common");
export const layout: {
    V: any;
    O: any;
    R: any;
    D: any;
    e: any;
    h: any;
    H: any;
    n: any;
    p: any;
    b: any;
    t: any;
    c: any;
    u: any;
    v: any;
    T: any;
    C: any;
    w: any;
    s: any;
    f: any;
    M: any;
};
