export const name: string;
export const core: string;
export const organization: string;
export const currency: string;
export const unit: string;
export const base: string;
export const cfg: string;
export const version: any;
export const url: string;
