export namespace wdb {
    const V: any;
    const O: any;
    const R: any;
    const D: any;
    const p: any;
    const P: any;
    const r: any;
    const w: any;
    const W: any;
    const l: any;
    const a: any;
    const i: any;
    const n: any;
    const h: any;
    const b: any;
    const o: any;
    const T: any;
    const t: any;
    const N: any;
    const M: any;
}
export namespace txdb {
    export const prefix: any;
    const R_1: any;
    export { R_1 as R };
    const r_1: any;
    export { r_1 as r };
    const t_1: any;
    export { t_1 as t };
    export const c: any;
    export const d: any;
    export const s: any;
    const p_1: any;
    export { p_1 as p };
    export const m: any;
    const h_1: any;
    export { h_1 as h };
    const T_1: any;
    export { T_1 as T };
    const P_1: any;
    export { P_1 as P };
    const M_1: any;
    export { M_1 as M };
    export const H: any;
    export const C: any;
    const b_1: any;
    export { b_1 as b };
    export const A: any;
    export const U: any;
    const i_1: any;
    export { i_1 as i };
    export const B: any;
    export const v: any;
    const o_1: any;
    export { o_1 as o };
}
